CREATE DATABASE CLASSDB;

USE CLASSDB;

DROP TABLE IF EXISTS `regTable`;

CREATE TABLE `regTable` (

  `REG_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,

  `FNAME` VARCHAR(10) NOT NULL,

  `LNAME` VARCHAR(20) NOT NULL,

  `MNAME` VARCHAR(20) NOT NULL,

  `DOB` VARCHAR(8) NOT NULL,

  `CLASSNAME` VARCHAR(20) NOT NULL,
  
  `LGNAME` VARCHAR(20) NOT NULL,

  `LGPASS` VARCHAR(20) NOT NULL,

   `ADDR1` VARCHAR(20) NOT NULL,

  `ADDR2` VARCHAR(20) DEFAULT NULL,

  `CITY` VARCHAR(20) NOT NULL,

  `STATE` VARCHAR(10) NOT NULL,

  `COUNTRY` VARCHAR(10) NOT NULL,

  `PHONE1` VARCHAR(10) NOT NULL,

  `PHONE2` VARCHAR(10) DEFAULT NULL,
  
  `REGISTRATIONDATE` VARCHAR(10) NOT NULL,
  
  `STARTDATE` VARCHAR(10) DEFAULT NULL,
  
  `ENDDATE` VARCHAR(10) DEFAULT NULL,
  
  `RENEWEDDATES` VARCHAR(100) DEFAULT NULL,

   PRIMARY KEY (`REG_ID`) USING BTREE,
  
   UNIQUE KEY `UNI_PHONE1` (`PHONE1`)

  ) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;